name: Firebase Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install Dependencies
        run: |
          cd functions 
          npm install

      - name: Install Firebase Tools
        run: npm install -g firebase-tools@latest
      
      - name: Deploy Functions to Firebase
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          firebase deploy --only functions --token ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
